# Generated by Django 4.2.5 on 2024-06-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.TextField(default="null"),
        ),
        migrations.AddField(
            model_name="user",
            name="signature",
            field=models.CharField(default="这个人很懒，什么都没有留下", max_length=100),
        ),
    ]
